### ISSUE TITLE
filename and line number

### ISSUE THREAD

**Issue by tansaku** [unjs/consola#113]
I'm wondering if there's a way to have consola logs automatically include information such as the filename and line number that the logging statement is on?

at the moment I'm struggling to set different reporter types on the server side - should the following work?

```
const consola = require('consola')
consola.setReporters([ new consola.WinstonReporter() ])
```

Whenever I try to set any alternate reporter type my app locks up without an obvious error?

**Comment by samtgarson** [comment]
If using Nuxt plugins as described in [this comment](https://github.com/unjs/consola/issues/114#issuecomment-800407491), you can either:
- create 2 separate plugins, one for client and one for server (instructions in the docs linked in that issue)
- use the `isClient` attribute of the context (first argument passed to the plugin export) to use different options based on server/client 👍 [(docs)](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#extend)

**Comment by samtgarson** [comment]
Can't speak to the errors on server side, sorry 🙈
