### ISSUE TITLE
is there a way to require consola throughout nuxt app in order to avoid requiring in each file?

### ISSUE THREAD

**Issue by tansaku** [unjs/consola#114]
Just wondering if there's a simple way to require consola in, say, nuxt.config.js in such a way that it's available throughout a nuxt project without having to require it in every file?

**Comment by samtgarson** [comment]
You can use a [Nuxt plugin](https://nuxtjs.org/docs/2.x/directory-structure/plugins/) and the `inject` function to inject the consola instance into every Vue context, e.g.

```js

const logger = {{ instantiate consola with options }}
export default ({ app }, inject) => {
  inject('logger', logger)
}

// in components:
export default {
  methods {
    someMethod () {
      this.$logger('mounted')
    }
  },
  asyncData({ app, $logger }) {
    $logger('asyncData')
    // If using Nuxt <= 2.12, use 👇
    app.$hello('asyncData')
  }
}
```

**Comment by husayt** [comment]
@pi0 I am sorry if I missed this, but was consola ever added to nuxt? A lot passed since this message, but I wonder what is recommended to be used inside nuxt for client side logging?

Thank you
