### ISSUE TITLE
`stdout` is undefined in worker context

### ISSUE THREAD

**Issue by manniL** [unjs/consola#115]
https://github.com/unjs/consola/blob/4477e87a5153d31d22a2692565959d90599a6b61/src/reporters/basic.js#L63

Hey 👋🏻
When using consola with Nitro I noticed that errors are being thrown when consola should log messages because `stdout` seems to be undefined in the worker context.

I think excluding consola from CF builds could be a good idea 🤔

**Comment by pi0** [comment]
Consola (node entry) is supposed to only run in NodeJS environment. Nuxt nitro should already have it replaced if not please open an issue in framework :)

**Comment by manniL** [comment]
Will do and close here 😋
