### ISSUE TITLE
logObj message is empty in build process during errors

### ISSUE THREAD

**Issue by vaschindler** [unjs/consola#118]
Hi,
in my nuxt.config.js I am setting consola.setReporter to define my own Reporter and format the log messages to JSON. 
This works fine. But when executing nuxt build and there are errors on build, no error messages are shown. 
I am already combining the logObj args to handle the messages, but on build errors they won't show up.

{"level":"error","message":{},"args":[],"dd":{"service":"test"}}

When I comment out the consola part in nuxt.config.js a fatal box with error message is normally shown.

Is this possible to pipe those build errors to the consola reporter?

**Comment by gkatsanos** [comment]
same problem.

**Comment by pi0** [comment]
Hi. Please provide a reproduction 🙏🏼
