### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by RJFelix** [unjs/consola#120]
Thanks for the great library!

This library appears to be missing a LICENSE file. I see that the license is MIT, but for attribution & legal purposes a full LICENSE file would be preferred so we can identify the copyright holder(s) and dates of copyright when distributing copies.

**Comment by pi0** [comment]
Hi @RJFelix. Thanks for the notice. Normally for NPM packages, [package.json:license](https://github.com/unjs/consola/blob/4477e87a5153d31d22a2692565959d90599a6b61/package.json#L5) field determines it but LICENSE file also added by #121
