### ISSUE TITLE
Sync or Async?

### ISSUE THREAD

**Issue by chrisschaub** [unjs/consola#132]
Is consola asynchronous or sync? Trying to replace console.log in my applications. I read the docs and couldn't find an answer. From the code, it seems like I can just
```
const myLogger = consola.create({
	_async: true
});
```

**Comment by pi0** [comment]
Hi. Logging is sync. Consola v3 will drop global `async` flag to avoid confusion. 

Later we might add a reporter option for async stream writes only.
