### ISSUE TITLE
consola +  cross-env doesn't output right

### ISSUE THREAD

**Issue by tjx666** [unjs/consola#157]
```typescript
import consola from 'consola';

consola.success('666')
```

```sh
cross-env NODE_ENV=test ts-node consola.ts
```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/195428013-498bcbad-7fa8-445a-ae11-08c9a09b0ab8.png">

**Comment by pi0** [comment]
Testing last version, cross-env does not makes issues and Fancy reporter works. But please note that setting `NODE_ENV` to `test` causes less verbose logs. And also if TTY is not available, basic reporter will be used.

Feel free to open a new issue if you feel consola v3 behavior could be better.
