### ISSUE TITLE
Consola.create does not work with nuxt3

### ISSUE THREAD

**Issue by JBustin** [unjs/consola#164]
### Environment

nuxt: 3.1.x
consola: 2.15.3

### Reproduction

https://stackblitz.com/edit/github-zuml8a?file=server/middleware/logger.ts

### Describe the bug

In a server middleware, I can use consola logger by directly doing `consola.info(...)`.
But I do not succeed to log by using the factory `const logger = consola.create()`.

### Additional context

I'm working to migrate a large application from nuxt2 to nuxt3.
I guess my logger imported from nuxt2 version does not work for this reason.
The code of the sandbox is a simplified version. I need a factory to configure my logger, I can not use the format `consola[verb]`.

**Comment by JBustin** [comment]
Hello contributors or community, is there anything else I can do to get help for this basic feature ?

**Comment by pi0** [comment]
Hi. Nuxt 3 mocks consola for server/nitro builds that is why some functions like `create` do not exist. I have created upstream issue to track from there https://github.com/unjs/unenv/issues/93

**Comment by JBustin** [comment]
@pi0 thanks for the resolution.
I have updated nuxt and consola to latest, unenv is in 1.4.1.
The code of my logger is really basic.

```js
import { createConsola } from 'consola'
...
const consolaTransport = (config): Transport => createConsola(config)
```

I'm trying to use `createConsola`, but I get this error when the dev server starts:

```sh
  import { createConsola } from 'node_modules/unenv/runtime/npm/consola.mjs';
  ^^^^^^^^^^^^^
  SyntaxError: The requested module 'node_modules/unenv/runtime/npm/consola.mjs' does not provide an export named 'createConsola'
```

Is there something I miss ?
