### ISSUE TITLE
Add error.cause support

### ISSUE THREAD

**Issue by navin-moorthy** [unjs/consola#202]
### Describe the feature

Expected behaviour mentioned in the issue - https://github.com/denoland/deno/issues/13413

<img width="641" alt="image" src="https://github.com/unjs/consola/assets/39694575/ab284f06-3be5-4faf-ab6e-428e1f954d32">

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
For reference also: https://v8.dev/features/error-cause

(PR is more than welcome. Let me know if you like to help on supporting and need some help)

**Comment by kongmoumou** [comment]
I also want this feature. It's really helpful for debugging root cause if the error was wrapped and re-thrown.
Looking forward to ur reponse for pr #308 . 🫡
