### ISSUE TITLE
The new underlining feature from #191 is a breaking change

### ISSUE THREAD

**Issue by trevor-vaughan** [unjs/consola#203]
### Environment

All

### Reproduction

```javascript
logger = require('consola')

myobj = { foo: 'my_content', bar: 'should_not_be_underlined' }
logger.log(myobj)
```

## 3.1.0 Output
```bash
{ foo: 'my_content', bar: 'should_not_be_underlined' }
```
## 3.2.0 Output

```bash
{ foo: 'mycontent', bar: 'shouldnotbeunderlined' }
```

### Describe the bug

The console output from 3.2.0 does not match the output from 3.1.0.

Ideally, fancy formatting would be opt-in instead of opt-out at runtime.

**Comment by trevor-vaughan** [comment]
Ah, I see that I should use `consola/basic` instead.

**Comment by trevor-vaughan** [comment]
Ah, no, I need to re-open this. I want the fancy formatting in terms of error messages, etc. But I definitely do not want object dumps to be processed as "fancy".

**Comment by pi0** [comment]
Sorry for the regression. Fixing soon

<img width="1162" alt="image" src="https://github.com/unjs/consola/assets/5158436/32dfba54-25bf-4a47-b37c-95b6c460bac0">

**Comment by trevor-vaughan** [comment]
@pi0 No worries, appreciate both the awesome tool and rapid response :-D.

FWIW, I *do* like the concept that was introduced, I just think that it needs to be selectively opt-in.

**Comment by pi0** [comment]
No worries. Can you please test with latest version? Is it still problematic for you?

**Comment by trevor-vaughan** [comment]
@pi0 Good to go! Appreciate the quick turnaround.
