### ISSUE TITLE
FATAL Intl.Segmenter is not a constructor with Node 14

### ISSUE THREAD

**Issue by dockleryxk** [unjs/consola#204]
### Environment

Node 14.12.4, trying to build a Nuxt 2 project

### Reproduction

Unfortunately, this is a private repo

### Describe the bug

Build a Nuxt 2 project on Node 14 using consola v3.2.x – get this fatal error.

If I can provide more context, please let me know, but this seems cut and dry. 

I did not try other Node versions

### Additional context

When forcing consola v3.1.x, there is no issue

### Logs

```sh
12:48:36
   FATAL  Intl.Segmenter is not a constructor
12:48:36
  
12:48:36
    at stringWidth (node_modules/@nuxt/cli/node_modules/consola/dist/shared/consola.2a3942ff.cjs:464:37)
12:48:36
    at FancyReporter.formatLogObj (node_modules/@nuxt/cli/node_modules/consola/dist/shared/consola.2a3942ff.cjs:585:41)
12:48:36
    at FancyReporter.log (node_modules/@nuxt/cli/node_modules/consola/dist/shared/consola.deac7d5a.cjs:53:23)
12:48:36
    at Consola._log (node_modules/@nuxt/cli/node_modules/consola/dist/core.cjs:383:16)
12:48:36
    at resolveLog (node_modules/@nuxt/cli/node_modules/consola/dist/core.cjs:351:14)
12:48:36
    at Consola._logFn (node_modules/@nuxt/cli/node_modules/consola/dist/core.cjs:379:5)
12:48:36
    at Consola.fatal (node_modules/@nuxt/cli/node_modules/consola/dist/core.cjs:308:19)
12:48:36
    at NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:366:17)
```

**Comment by wilhantian** [comment]
me too...

**Comment by maxJeongCC** [comment]
me too..too!

**Comment by pi0** [comment]
3.2.2 has a workaround for Node 14 backward compatibility (https://github.com/unjs/consola/releases/tag/v3.2.2)

**Comment by dockleryxk** [comment]
@pi0 thank you for adding this workaround – I'm sure it's annoying supporting an EOL version but it's very much appreciated!

**Comment by jk-soul** [comment]
> 3.2.2 has a workaround for Node 14 backward compatibility (https://github.com/unjs/consola/releases/tag/v3.2.2)

show again in 3.30 :)

**Comment by xiaoyierle** [comment]
show again in 3.2.3

**Comment by xiaoyierle** [comment]
Version 3.2.3 is sufficient to support

**Comment by xiaoyierle** [comment]
In the nuxt2.14.0 version, the 3.2.3 version of Consola was referenced, which caused the failure to start successfully in Node 14. Can you help to handle compatibility with this version?

**Comment by fenn1ks** [comment]
in 3.3.3 version again this problem, all project crash

**Comment by pi0** [comment]
#326  / [v3.1.1](https://github.com/unjs/consola/releases/tag/v3.3.1 adds fallback for `Intl`, however, please consider that Node.js 14 is long time EOL and there is no guarantee consola won't break again on unsupported node versions. Please consider upgrading ASAP to a supported version.

**Comment by chenyinshi** [comment]
Hello, I am using Node v14.21.2. The project was previously using consola v3.2.3, which worked fine, but after upgrading to v3.3.0 yesterday, I encountered the error 'FATAL Intl.Segmenter is not a constructor'. I have upgraded to v3.3.1, but the same issue persists.

**Comment by xiaoyierle** [comment]
My project is based on node 14.19.1 version and uses npm i to pull dependencies, using the nuxt 2.14.0 framework
After pulling the code, it is necessary to modify the folder 'node_comodules/@ nuxt'
```
node_modules/@nuxt/utils/node_modules/consola
node_modules/@nuxt/config/node_modules/consola
node_modules/@nuxt/cli/node_modules/consola
node_modules/@nuxt/core/node_modules/consola
node_modules/@nuxt/server/node_modules/consola
node_modules/@nuxt/vue-renderer/node_modules/consola
node_modules/@nuxt/telemetry/node_modules/consola
node_modules/@nuxt/builder/node_modules/consola
node_modules/@nuxt/webpack/node_modules/consola
node_modules/webpackbar/node_modules/consola
```
The 'console' version in the code is ‘3.2.3' with syntax issues and needs to be downgraded to '3.2.2'`
The downgrade method is to replace all files in the 'node_comodules/console' folder with the version number in the above folder, which can be viewed in 'package. json'
