### ISSUE TITLE
I would like to be able to determine the 'friendly' name of the log level from the numeric level

### ISSUE THREAD

**Issue by trevor-vaughan** [unjs/consola#208]
### Describe the feature

The default level is `3` but that isn't very user-friendly when trying to pass it back to users.

I would like to be able to lookup the 'friendly' name of the level from the current `level` setting.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by NozomuIkuta** [comment]
@trevor-vaughan 

At the moment, you could look up string name of log level by searching `LogLevel` constants:

```ts
import { LogLevels } from 'consola'

const [levelName, _] = Object.entries(LogLevels).find(([levelName, levelNum]) => levelNum === <certain_num>)

levelName // 'debug'
```

Ref: https://github.com/unjs/consola/blob/c2ff2b6d610b2442768ed01cd9aede21fff7fdb9/src/constants.ts

---

Exporting such a utility function from consola would be enhancement in terms of DX.

**Comment by NozomuIkuta** [comment]
I noticed that we have to take it into consideration that more than one keys (i.e. `LogType`) are associated with a number.

https://github.com/unjs/consola/blob/c2ff2b6d610b2442768ed01cd9aede21fff7fdb9/src/constants.ts#L6-L28

So, there seems to be no (easy) way a function can determine which `LogType` is actually meant by a number. 🤔

**Comment by trevor-vaughan** [comment]
@NozomuIkuta Hmm...maybe return the 'most common' one?

For example, for `3` I would expect `info` with the others as aliases.

**Comment by pi0** [comment]
as @nozomuikuta mentioned, multiple `types` are assignable to each `level`. `level` controls verbosity and while not much human friendly, it is a standard in logging systems.
