### ISSUE TITLE
Support custom prompt

### ISSUE THREAD

**Issue by 13OnTheCode** [unjs/consola#215]
### Describe the feature

Currently, it seems that only the built-in prompts in Clack are supported. If I customize a prompt, I would like to integrate it into Consola for use. Is it possible to achieve this?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. You can provide a custom prompt factory as `prompt` option to `createConsola` (see here https://github.com/unjs/consola/blob/main/src/index.ts#L25). But i recommend to keep using built-in behavior for CLI experience consistency.
