### ISSUE TITLE
Issue with prompt (clack) cancellation detect

### ISSUE THREAD

**Issue by samuelstroschein** [unjs/consola#251]
### Environment

/

### Reproduction

- https://github.com/natemoo-re/clack/issues/83#issuecomment-1564470873
- https://github.com/unjs/consola/issues/234
- https://github.com/unjs/consola/issues/239

### Describe the bug

Consola bundles the NPM package, leading to downstream bugs. 

## Proposal 

Stop bundling consola.

If bundling is important, the consumer of consola can use a bundler. A consumer using a bundler means the complexity of consola is reduced, bugs that bundling consola introduces are removed, and consola becomes more useful.

**Comment by samuelstroschein** [comment]
Hi @pi0,

Thanks for the response. The bundling/inlining seems to cause bugs, though; see https://github.com/unjs/consola/issues/234 and https://github.com/natemoo-re/clack/issues/83#issuecomment-1564470873 specifically.  

I don't have enough background to evaluate whether bundling is worth the ecosystem impact.

**Comment by pi0** [comment]
Thanks for clarification by linking issue. I have shared a suggestion for them there.

We can easily solve it earlier for consola btw as consola API is dedicated to itself .

**Comment by samuelstroschein** [comment]
I got it working btw

https://github.com/inlang/monorepo/blob/02856c466a9198c1ccf9d277af3189bb18a42f3c/inlang/source-code/paraglide/paraglide-js/src/cli/commands/init.ts#L308-L314

**Comment by pi0** [comment]
nice workaround!
