### ISSUE TITLE
`initial` prop doesn't seem to work

### ISSUE THREAD

**Issue by warflash** [unjs/consola#274]
### Environment

node: v18.18.0
consola: 3.2.3 

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-wxmucj?file=index.js,package.json

### Describe the bug

Setting the initial prop of promps doesn't seem to work. The repro above is taken from the example code in the repo https://github.com/unjs/consola/blob/main/examples/prompt.ts

**Comment by peterroe** [comment]
I looked hard to find out why.

I find the `consola/dist/chunks/prompt.mjs` file produced by the repository building and the one distributed via npm are different.

In https://www.npmjs.com/package/consola?activeTab=code file:consola/dist/chunks/prompt.mjs  line: 409-425

The expected product should be:

```diff
  if (opts.type === "select") {
    return await select({
      message,
      options: opts.options.map(
        (o) => typeof o === "string" ? { value: o, label: o } : o
      )
+     initialValue: opts.initial
    });
  }
  if (opts.type === "multiselect") {
    return await multiselect({
      message,
      options: opts.options.map(
        (o) => typeof o === "string" ? { value: o, label: o } : o
      ),
      required: opts.required,
+      initialValue: opts.initial
    });
  }
```

**Comment by LekoArts** [comment]
You can install from GitHub so long, (e.g. with pnpm https://pnpm.io/cli/add#install-from-git-repository).

@pi0 Can you release a new version please? Thanks a lot!

**Comment by Winns** [comment]
Can this be fixed please ?

**Comment by odanado** [comment]
This problem has been resolved at https://github.com/unjs/consola/pull/232, but a new version has yet to be released.
