### ISSUE TITLE
Expose PromptOptions as a public API

### ISSUE THREAD

**Issue by vorant94** [unjs/consola#301]
### Describe the feature

`consola.prompt` accepts `PromptOptions` as a second argument. In my case i'd like to define options separately from prompt request to reuse them multiple times. Is there any reason why these interfaces aren't exported despite being a part of public facing API (`prompt` function signature)?

As a temporary workaround I use `satisfies Parameters<typeof consola.prompt>[1]`, but it is inconvenient comparing with just using `PromptOptions` and all this type union members right away... 

If these types can be exported, I'll be happy to make PR for it

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Will be exported in next release.
