### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Tom-cy** [unjs/consola#319]
### Describe the feature

  import { consola } from 'node_modules/consola/dist/consola.js';
  ^^^^^^^
  SyntaxError: The requested module 'node_modules/consola/dist/consola.js' does not provide an export named 'consola'
  
  
  who can tell what happennnnnnnnnnnnn

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by NozomuIkuta** [comment]
Would you provide a minimal reproduction or a link to repository, with instructions to reproduce?

By the way, in future, when you want to report that something doesn't work as expected, please use bug report issue template instead of feature request.
