### ISSUE TITLE
FATAL Intl.Segmenter is not a constructor with Node 14 after update 3.3.3

### ISSUE THREAD

**Issue by fenn1ks** [unjs/consola#327]
### Environment

Node 14.18.3

### Reproduction

----

### Describe the bug

the same https://github.com/unjs/consola/issues/204

### Additional context

Build a Nuxt 2 project on Node 14 using consola v3.3.3 – get this fatal error.

**Comment by pi0** [comment]
#326  / [v3.1.1](https://github.com/unjs/consola/releases/tag/v3.3.1) adds fallback for `Intl`, however, please consider that Node.js 14 is long time EOL and there is no guarantee consola won't break again on unsupported node versions. Please consider upgrading ASAP to a supported version.

**Comment by fenn1ks** [comment]
> #326 / [v3.1.1](https://github.com/unjs/consola/releases/tag/v3.3.1) adds fallback for `Intl`, however, please consider that Node.js 14 is long time EOL and there is no guarantee consola won't break again on unsupported node versions. Please consider upgrading ASAP to a supported version.

It turns out that this path should work automatically? 

I don't use this module directly, other modules use it as a dependency... and when the project started to crash, I checked and saw that all dependencies had been updated to 3.3.3

**Comment by pi0** [comment]
(you need to dedup or recreate package manager lockfile) -- regardless of using direct or indirect please consider upgrading Node alongside.
