### ISSUE TITLE
FATAL Intl.Segmenter is not a constructor with Node 14

### ISSUE THREAD

**Issue by chenyinshi** [unjs/consola#328]
### Environment

node v14.21.2
consola v3.3.0 or consola v3.3.1

### Reproduction

node v14.21.2
consola v3.3.0 or consola v3.3.1

### Describe the bug

I am using Node v14.21.2. The project was previously using consola v3.2.3, which worked fine, but after upgrading to v3.3.0 yesterday, I encountered the error 'FATAL Intl.Segmenter is not a constructor'. I have upgraded to v3.3.1, but the same issue persists.

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the src/index.ts file to include a fallback for environments that don't support Intl.Segmenter, such as Node.js v14. This change ensures compatibility with older Node.js versions while maintaining functionality for newer environments.

You can review changes in this commit: https://github.com/jacks-sam1010/unjs-consola-328/commit/3b28593275b8955a3f4c525570572b93c5c45dc1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by donne1226** [comment]
same iuuse

**Comment by helpceo** [comment]
same iuuse

**Comment by xiaoyierle** [comment]
My project is based on node 14.19.1 version and uses npm i to pull dependencies, using the nuxt 2.14.0 framework
After pulling the code, it is necessary to modify the folder 'node_comodules/@ nuxt'
```
node_modules/@nuxt/utils/node_modules/consola
node_modules/@nuxt/config/node_modules/consola
node_modules/@nuxt/cli/node_modules/consola
node_modules/@nuxt/core/node_modules/consola
node_modules/@nuxt/server/node_modules/consola
node_modules/@nuxt/vue-renderer/node_modules/consola
node_modules/@nuxt/telemetry/node_modules/consola
node_modules/@nuxt/builder/node_modules/consola
node_modules/@nuxt/webpack/node_modules/consola
node_modules/webpackbar/node_modules/consola
```
The 'consola' version in the code will report an error if it is' 3.2.3 'and needs to be downgraded to' 3.2.2 '`
The downgrade method is to replace all files in the 'node_comodules/consola' folder with the version number in the above folder, which can be viewed in 'package. json'

**Comment by donne1226** [comment]
> My project is based on node 14.19.1 version and uses npm i to pull dependencies, using the nuxt 2.14.0 framework After pulling the code, it is necessary to modify the folder 'node_comodules/@ nuxt'
> 
> ```
> node_modules/@nuxt/utils/node_modules/consola
> node_modules/@nuxt/config/node_modules/consola
> node_modules/@nuxt/cli/node_modules/consola
> node_modules/@nuxt/core/node_modules/consola
> node_modules/@nuxt/server/node_modules/consola
> node_modules/@nuxt/vue-renderer/node_modules/consola
> node_modules/@nuxt/telemetry/node_modules/consola
> node_modules/@nuxt/builder/node_modules/consola
> node_modules/@nuxt/webpack/node_modules/consola
> node_modules/webpackbar/node_modules/consola
> ```
> 
> The 'consola' version in the code will report an error if it is' 3.2.3 'and needs to be downgraded to' 3.2.2 '` The downgrade method is to replace all files in the 'node_comodules/consola' folder with the version number in the above folder, which can be viewed in 'package. json'

It can be done, but it’s really not a very elegant way. I upgrade my node version to 16

**Comment by pi0** [comment]
https://github.com/unjs/consola/releases/tag/v3.3.2
