### ISSUE TITLE
Uncaught TypeError: Illegal invocation while log.apply(void 0, ...

### ISSUE THREAD

**Issue by duyleekun** [unjs/consola#52]
### Version

[2.8.1](https://github.com/consola/releases/tag/2.8.1)

### Reproduction link

[http://not-available.com/Always broken on webview android 6.0.0](http://not-available.com/Always broken on webview android 6.0.0)

### Steps to reproduce

Using android emulator with version 6.0.0

Having any consola.log will result in Uncaught TypeError: Illegal invocation due to https://stackoverflow.com/questions/8159233/typeerror-illegal-invocation-on-console-log-apply/8159338#8159338

The related snippet in consola/dist/consola.browser.js is 

```javascript
                return r(t, [{
                    key: "log",
                    value: function(e) {
                        var t = e.level < 1 ? console.__error || console.error : 1 === e.level && console.warn ? console.__warn || console.warn : console.__log || console.log
                          , r = "log" !== e.type ? e.type : ""
                          , s = e.tag ? e.tag : ""
                          , n = this.typeColorMap[e.type] || this.levelColorMap[e.level] || this.defaultColor
                          , i = "\n      background: ".concat(n, ";\n      border-radius: 0.5em;\n      color: white;\n      font-weight: bold;\n      padding: 2px 0.5em;\n    ");
                        t.apply(void 0, ["%c" + [s, r].filter(Boolean).join(":"), i].concat(o(e.args)))
                    }
                }]),
```

### What is expected ?

Not throwing any exception in old browser

### What is actually happening?

Throwing Uncaught TypeError: Illegal invocation

### Additional comments?

Replace `void 0` with `console` will resolve this for my case

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c50">#c50</a>)</em></sub></div>

**Comment by pimlie** [comment]
This will mostly likely be a similar issue in (at least) IE9 as well. Its caused by using a spread operator in the source like `console.log(...args)`. This should be transpiled to a `console.log.apply(console, args)` but you cant call apply on console.log in IE9

**Comment by pi0** [comment]
Closing as this is an old issue. Feel free to create if still having issues with consola v3 🙏🏼
