### ISSUE TITLE
SyntaxError: Unexpected token ... on node 6.10.3

### ISSUE THREAD

**Issue by parth444** [unjs/consola#56]
### Version

[v2.9.0](https://github.com/consola/releases/tag/v2.9.0)

### Reproduction link

[No link needed](No link needed)

### Steps to reproduce

Create a file test.js and add following line:
```
var consola = require('consola');
```

### What is expected ?

No errors when running on node 6.10.3

### What is actually happening?

```
(function (exports, require, module, __filename, __dirname) { "use strict";function _interopDefault(u){return u&&"object"==typeof u&&"default"in u?u.default:u}var util=_int
eropDefault(require("util")),path=require("path"),fs=require("fs"),os=_interopDefault(require("os")),commonjsGlobal="undefined"!=typeof globalThis?globalThis:"undefined"!=t
ypeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:{};function createCommonjsModule(u,e){return u(e={exports:{}},e.exports),e.exports}funct
ion getCjsExportFromNamespace(u){return u&&u.default||u}var vendors=[{name:"AppVeyor",constant:"APPVEYOR",env:"APPVEYOR",pr:"APPVEYOR_PULL_REQUEST_NUMBER"},{name:"Bamboo",c
onstant:"BAMBOO",env:"bamboo_planKey"},{name:"Bitbucket Pipelines",constant:"BITBUCKET",env:"BITBUCKET_COMMIT"},{name:"Bitrise",constant:"BITRISE",env:"BITRISE_IO",pr:"BITR
ISE_PULL_REQUEST"},{name:"Buddy",constant:"BUDDY",env:"BUDDY_WORKSPACE_ID",pr:"BUDD
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Default\Desktop\test.js:1:77)
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c54">#c54</a>)</em></sub></div>

**Comment by temitopeadesoji** [comment]
please is there any solution for this? im having the same issue

**Comment by bobdenotter** [comment]
This is also breaking our builds. Subscribing and hopeful for a quick fix. :-)

**Comment by bobdenotter** [comment]
We've managed to fix (or circumvent) this issue in our project by bumping the version of node from 8.2 to 12.5.

**Comment by Sly-Little-Fox** [comment]
Consola is using the spread operator, which is not supported in node 6 (in this case). A solution would be to either upgrade node or run consola through babel. (https://babel.dev/repl#?browsers=node%206&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=MYewdgziA2CmB00QHMAUBveWCGuC-AlEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%7D)

**Comment by pi0** [comment]
closing as this is an old issue. latest LTS node is recommended
