### ISSUE TITLE
Fancy reporter hides nested structures

### ISSUE THREAD

**Issue by krzkaczor** [unjs/consola#73]
### Version

[v2.10.0](https://github.com/consola/releases/tag/v2.10.0)

### Reproduction link

[https://repl.it/repls/RealDarkredOolanguage](https://repl.it/repls/RealDarkredOolanguage)

### Steps to reproduce

Create deeply (4 levels) nested object and try to log it. 

### What is expected ?

Whole object gets logged in the console.

### What is actually happening?

Object is collapsed and part of it becomes simply [Object] hiding important info.

### Additional comments?

This could be a configurable behaviour but I strongly belive that by default everything should be visible.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/consola/issues/c61">#c61</a>)</em></sub></div>

**Comment by dora-gt** [comment]
I don't think this is a bug but I would like to specify a parameter like `deep`.

**Comment by pi0** [comment]
Consola v3 allows this via `formatOptions` top level.
